//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSED06_HotelDatabaseManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billing
    {
        public int BillingID { get; set; }
        public int BookingRoomJoinIDFK { get; set; }
        public Nullable<int> BarCharge { get; set; }
        public Nullable<int> WiFiCharge { get; set; }
        public Nullable<int> PhoneCharge { get; set; }
        public Nullable<int> RoomCharge { get; set; }
        public bool BillingPaid { get; set; }
    
        public virtual BookingRoomJoin BookingRoomJoin { get; set; }
    }
}
