//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSED06_HotelDatabaseManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingRoomJoin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookingRoomJoin()
        {
            this.Billings = new HashSet<Billing>();
        }
    
        public int ID { get; set; }
        public int BookingIDFK { get; set; }
        public int RoomIDFK { get; set; }
        public int NumberOfGuests { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Billing> Billings { get; set; }
        public virtual Booking Booking { get; set; }
        public virtual Room Room { get; set; }
    }
}
