//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSED06_HotelDatabaseManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.BookingRoomJoins = new HashSet<BookingRoomJoin>();
        }
    
        public int RoomID { get; set; }
        public Nullable<int> RoomNumSingleBeds { get; set; }
        public Nullable<int> RoomNumDoubleBeds { get; set; }
        public int RoomBaseTariff { get; set; }
        public int RoomExtraPersonRate { get; set; }
        public string RoomExtraFeatures { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingRoomJoin> BookingRoomJoins { get; set; }
    }
}
